### ISSUE TITLE
Unable to view testing tab on frontend 

### ISSUE THREAD

**Issue by dmdhrumilmistry** [metlo-labs/metlo#294]
I've previously deployed metlo using docker and I've ensured that I'm running latest images using

```bash
$ python3 manage-deployment.py update            
Pulling Docker Images...
Using default tag: latest
latest: Pulling from metlo/backend
Digest: sha256:60e16f21d066eb93f40d4187be4fe0982d7bd8dbc5212ef9732e7d61d8c7aaef
Status: Image is up to date for metlo/backend:latest
docker.io/metlo/backend:latest
Using default tag: latest
latest: Pulling from metlo/frontend
Digest: sha256:03f6a763e4ed2ed71e5d16fb30ee9c1eba090c4abc533909b9f0cd7ffb4404e8
Status: Image is up to date for metlo/frontend:latest
docker.io/metlo/frontend:latest
Using default tag: latest
latest: Pulling from metlo/jobrunner
Digest: sha256:f47b487634270cd7714d472cd7c2c68171e18b8ca4e661a957a6b5a83cfb9817
Status: Image is up to date for metlo/jobrunner:latest
docker.io/metlo/jobrunner:latest
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.13) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Stopping metlo-analyzer ... done
Stopping metlo-jobs     ... done
Stopping metlo-backend  ... done
Stopping metlo-ingestor ... done
Stopping metlo_db_1     ... done
Stopping metlo_cache_1  ... done
Stopping metlo-frontend ... done
Removing metlo-analyzer ... done
Removing metlo-jobs     ... done
Removing metlo-backend  ... done
Removing metlo-ingestor ... done
Removing metlo_db_1     ... done
Removing metlo_cache_1  ... done
Removing metlo-frontend ... done
Removing network metlo_default
Pulling Updated Files...
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.13) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1418, in connect
    super().connect()
  File "/usr/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage-deployment.py", line 170, in <module>
    main()
  File "manage-deployment.py", line 164, in main
    update()
  File "manage-deployment.py", line 128, in update
    update_files()
  File "manage-deployment.py", line 92, in update_files
    get_file(f)
  File "manage-deployment.py", line 24, in get_file
    with urllib.request.urlopen(request) as response:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>
```
> I get network unreachable error on running above command.

On starting metlo docker containers using `manage-deployment.py` file. I don't see any testing tab on dashboard. 
```bash
$ python3 manage-deployment.py start  
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.13) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Creating network "metlo_default" with the default driver
Creating metlo_db_1     ... done
Creating metlo_cache_1  ... done
Creating metlo-frontend ... done
Creating metlo-ingestor ... done
Creating metlo-backend  ... done
Creating metlo-analyzer ... done
Creating metlo-jobs     ... done
```

Ig I deployed metlo using docker before testing tab was introduced.

**Comment by akshay288** [comment]
Hey @dmdhrumilmistry the testing UI is only currently in the enterprise version, you can deploy it by going to https://my.metlo.com

Otherwise you should still be able to use our CLI to run and generate tests with the OS version :)

Sorry about that we'll make the docs more clear!

**Comment by dmdhrumilmistry** [comment]
ohh okay @akshay288 thank you for clarification.
