### ISSUE TITLE
DB error

### ISSUE THREAD

**Issue by eikaramba** [metlo-labs/metlo#32]
following installation instructions i get:
```
metlo-db-1      | 2022-10-14 11:41:09.171 UTC [1] LOG:  database system is ready to accept connections
metlo-jobs      | Migration "removeOwnerColumnFromApitrace1665697571667" failed, error: Table "api_trace" does not exist.
metlo-jobs      | /usr/src/app/backend/node_modules/typeorm/query-runner/BaseQueryRunner.js:193
metlo-jobs      |             throw new TypeORMError_1.TypeORMError(`Table "${tableName}" does not exist.`);
metlo-jobs      |                   ^
metlo-jobs      |
metlo-jobs      | TypeORMError: Table "api_trace" does not exist.
metlo-jobs      |     at PostgresQueryRunner.getCachedTable (/usr/src/app/backend/node_modules/typeorm/query-runner/BaseQueryRunner.js:193:19)
metlo-jobs      |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
metlo-jobs      |     at async PostgresQueryRunner.dropColumn (/usr/src/app/backend/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:1098:15)
metlo-jobs      |
metlo-jobs      | Node.js v18.10.0
metlo-jobs      | error Command failed with exit code 1.
metlo-jobs      | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
metlo-jobs exited with code 1
metlo-ingestor  | Migration "removeOwnerColumnFromApitrace1665697571667" failed, error: Table "api_trace" does not exis
```

**Comment by NikhilShahi** [comment]
Hey @eikaramba , let me take a look at this and get back to you.

**Comment by NikhilShahi** [comment]
Hey @eikaramba , sorry for the wait. Error should be gone now with the latest docker images.
