### ISSUE TITLE
Metlo cli - SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by r00t9** [metlo-labs/metlo#98]
I install metlo from npm 
```
npm i -g @metlo/cli
```
Server: Ubuntu 22.04.1 LTS
Nodejs: v12.22.9
Npm: 8.5.1
metlo: metlo/cli@0.0.5

**Error log**
```
metlo --help
/usr/local/lib/node_modules/@metlo/cli/node_modules/@aws-sdk/client-ec2/dist-cjs/protocols/Aws_ec2.js:22372
        if (input.TagSpecifications?.length === 0) {
                                    ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@metlo/cli/node_modules/@aws-sdk/client-ec2/dist-cjs/commands/AcceptAddressTransferCommand.js:8:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

**Comment by r00t9** [comment]
I get this error when i run `metlo` in general 
```
$ metlo 
/usr/local/lib/node_modules/@metlo/cli/node_modules/@aws-sdk/client-ec2/dist-cjs/protocols/Aws_ec2.js:22372
        if (input.TagSpecifications?.length === 0) {
                                    ^

SyntaxError: Unexpected token '.'
```

**Comment by AHarmlessPyro** [comment]
This seems to be an issue with nodejs v12. Could you try running metlo cli with more recent version of Node ?

**Comment by r00t9** [comment]
Is working fine thanks you :)

**Comment by AHarmlessPyro** [comment]
No problem ! Feel free to let us know how else we can help you 😄
